baseurl: "/"
languageCode: "en-us"
title: "hickv's blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 10
    - name: "Posts"
      url: "/posts/"
      weight: 20
    - name: "Projects"
      url: "/projects/"
      weight: 30
    - name: "Game Assets"
      url: "/game-assets/"
      weight: 40

params:
  lastmod: "2024-06-03"
  description: "A website built through Hugo and blogdown."
  copyright: "Luiz Henrique Lima Vieira"
  socials:
    - github:
      fa_icon: "fab fa-github fa-1x"
      href: "https://github.com/hickVieira"
    - linkedin:
      fa_icon: "fab fa-linkedin-in fa-1x"
      href: "https://www.linkedin.com/in/hick-vieira/"
    - email:
      fa_icon: "fab fa-at fa-1x"
      href: "mailto:lhlvieirag@gmail.com"
    - youtube:
      fa_icon: "fab fa-youtube fa-1x"
      href: "https://www.youtube.com/@gaemdevolper/videos"
    - itchio:
      fa_icon: "fab fa-itch-io fa-1x"
      href: "https://gaemdevolper.itch.io/"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
