baseurl: /
title: hickv's blog
languageCode: en-us
paginate: "10"
theme: binario
disqusShortname: ""
googleAnalytics: ""
menu:
  main:
    - name: "All Posts"
      url: "/posts/"
      weight: 10
    - name: "Projects"
      url: "/projects/"
      weight: 20
    - name: "Game Assets"
      url: "/game-assets/"
      weight: 30
  # footer:

services:
  disqus:
    shortname: ""
  googleAnalytics:
    ID: ""
Author:
  name: hickv
  bio: Programmer and hobbist gamedev.
  avatar: images/kitty.jpg
Params:
  description: Responsive card-based & code-light Hugo theme
  copyright: Luiz Henrique Lima Vieira
  opengraph: true
  schema: true
  twitter_cards: true
  columns: 3
  mainSections:
    - posts
  dateFormat: January 02, 2006
  colorTheme: ""
  # customCSS:
  # - css/custom.css
  # customJS:
  # - js/custom.js
  mainMenuAlignment: left
  authorbox: true
  comments: true
  related: true
  relatedMax: 5
  mathjax: true
  mathjaxPath: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js
  mathjaxConfig: TeX-AMS-MML_HTMLorMML
  hideNoPostsWarning: false
  Entry:
    meta:
      - date
      - categories
      - tags
    toc: false
    tocOpen: true
  Featured:
    previewOnly: false
  # Breadcrumb:
  #   enable: false
  #   homeText: hickv
  Social:
    - github:
      fa_icon: "fab fa-github fa-1x"
      href: "https://github.com/hickVieira"
    - linkedin:
      fa_icon: "fab fa-linkedin-in fa-1x"
      href: "https://www.linkedin.com/in/hick-vieira/"
    - email:
      fa_icon: "fab fa-at fa-1x"
      href: "mailto:lhlvieirag@gmail.com"
    - youtube:
      fa_icon: "fab fa-youtube fa-1x"
      href: "https://www.youtube.com/@gaemdevolper/videos"
    - itchio:
      fa_icon: "fab fa-itch-io fa-1x"
      href: "https://gaemdevolper.itch.io/"
  Manifest:
    name: Binario
    shortName: Binario
    display: browser
    startUrl: /
    backgroundColor: "#2a2a2a"
    themeColor: "#1b1b1b"
    description: Responsive card-based & code-light Hugo theme
    orientation: portrait
    scope: /
outputFormats:
  MANIFEST:
    mediaType: application/json
    baseName: manifest
    isPlainText: true
    notAlternative: true
outputs:
  home:
    - HTML
    - RSS
    - MANIFEST
